apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      nodeSelector:  # Add this section here
        cloud.google.com/gke-nodepool: vishnu-pool # Replace <my-pool> with your actual node pool name
      containers:
        - name: postgres
          image: postgres:latest
          args: ["-c", "config_file=/etc/postgresql/postgresql.conf"]
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: secret
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          resources:
            requests:
              memory: 4Gi
              cpu: 4
            limits:
              memory: 6Gi
              cpu: 4
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: conf
              mountPath: /etc/postgresql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-pv-claim
        - name: conf
          configMap:
            name: postgres-conf
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-conf
data:
  postgresql.conf: |
    shared_buffers = 4GB
    listen_addresses = '*'
